import React, { useState, useEffect } from 'react';
import FilterFields from '../components/FilterFields';
import FilterChips from '../components/FilterChips';
import LaptopTable from '../components/LaptopTable';
import LaptopDetailModal from '../components/LaptopDetailModal';

// MATERIAL-UI COMPONENTS
import {
    Container,
} from '@mui/material';

const dummyLaptopData = [
    {
        serial: "C02Z2C9MLYWG",
        laptopId: "2C9M",
        status: "DONATED",
        model: "MacBookAir8,2",
        screenSize: "13\"",
        cpuType: "1.60GHz i5",
        memory: "8 GB",
        diskSize: "128 GB",
        chargerType: "30W USB-C",
        chargerIncluded: true,
        condition: "B",
        value: "450",
        soldPrice: "",
        dateDonated: "",
        donatedBy: "BetterUP",
        notes: "Hard disk locked (message pops up to unlock disk, password hint has profanity)",
        listPrice: ""
    },
    {
        serial: "FVFZ7JTBLYWG",
        laptopId: "7JTB",
        status: "DONATED",
        model: "MacBookAir8,2",
        screenSize: "13\"",
        cpuType: "1.60GHz i5",
        memory: "8 GB",
        diskSize: "128 GB",
        chargerType: "30W USB-C",
        chargerIncluded: true,
        condition: "B",
        value: "450",
        soldPrice: "",
        dateDonated: "7/26/21",
        donatedBy: "BetterUP",
        notes: "Reserved for Precieux",
        listPrice: ""
    },
    {
        serial: "FVFYQ464LYWJ",
        laptopId: "Q464",
        status: "RECYCLE",
        model: "MacBookAir8,2",
        screenSize: "13\"",
        cpuType: "1.60GHz i5",
        memory: "8 GB",
        diskSize: "128 GB",
        chargerType: "30W USB-C",
        chargerIncluded: true,
        condition: "A",
        value: "450",
        soldPrice: "",
        dateDonated: "7/26/21",
        donatedBy: "BetterUP",
        notes: "",
        listPrice: ""
    },
    {
        serial: "FVFZ7FJZLYWG",
        laptopId: "7FJZ",
        status: "READY",
        model: "MacBookAir8,2",
        screenSize: "13\"",
        cpuType: "1.60GHz i5",
        memory: "8 GB",
        diskSize: "128 GB",
        chargerType: "30W USB-C",
        chargerIncluded: true,
        condition: "B",
        value: "450",
        soldPrice: "",
        dateDonated: "7/26/21",
        donatedBy: "BetterUP",
        notes: "Kenneth released as of 6/22",
        listPrice: ""
    },
    {
        serial: "FVFZL0HYL415",
        laptopId: "L0HY",
        status: "READY",
        model: "MacBookPro15,4",
        screenSize: "13\"",
        cpuType: "1.7GHz i7",
        memory: "16 GB",
        diskSize: "128 GB",
        chargerType: "61W USB-C",
        chargerIncluded: true,
        condition: "A",
        value: "960",
        soldPrice: "",
        dateDonated: "12/8/21",
        donatedBy: "BetterUP",
        notes: "Kenneth released as of 6/22",
        listPrice: ""
    },
    {
        serial: "FVFZL0HYL415",
        laptopId: "L0HY",
        status: "DONATED",
        model: "MacbookPro",
        screenSize: "13\"",
        cpuType: "",
        memory: "8 GB",
        diskSize: "256 GB",
        chargerType: "20.3 W USB-C",
        chargerIncluded: false,
        condition: "A",
        value: "300",
        soldPrice: "",
        dateDonated: "",
        donatedBy: "BetterUP",
        notes: "",
        listPrice: ""
    },
    {
        serial: "FVFC90E4LYWP",
        laptopId: "9.00E+05",
        status: "DONATED",
        model: "MacBookAir8,2",
        screenSize: "13\"",
        cpuType: "1.60GHz i5",
        memory: "8 GB",
        diskSize: "256 GB",
        chargerType: "30W USB-C",
        chargerIncluded: true,
        condition: "A",
        value: "480",
        soldPrice: "",
        dateDonated: "7/26/21",
        donatedBy: "BetterUP",
        notes: "Reserved for Christian Perry",
        listPrice: ""
    },
    {
        serial: "C02Y53WRJK78",
        laptopId: "53WR",
        status: "DONATED",
        model: "MacBookAir8,1",
        screenSize: "13\"",
        cpuType: "1.60GHz i5",
        memory: "8 GB",
        diskSize: "256 GB",
        chargerType: "30W USB-C",
        chargerIncluded: true,
        condition: "A",
        value: "420",
        soldPrice: "",
        dateDonated: "7/26/21",
        donatedBy: "BetterUP",
        notes: "Reserved for Jaxon Perry",
        listPrice: ""
    },
    {
        serial: "C02Y62N9JK78",
        laptopId: "62N9",
        status: "DONATED",
        model: "MacBookAir8,1",
        screenSize: "13\"",
        cpuType: "1.60GHz i5",
        memory: "8 GB",
        diskSize: "256 GB",
        chargerType: "30W USB-C",
        chargerIncluded: true,
        condition: "B",
        value: "420",
        soldPrice: "",
        dateDonated: "7/26/21",
        donatedBy: "BetterUP",
        notes: "Reserved for Solomon Perry",
        listPrice: ""
    },
    {
        serial: "FVFYQ1CBJK78",
        laptopId: "Q1CB",
        status: "READY",
        model: "MacBookAir8,1",
        screenSize: "13\"",
        cpuType: "1.60GHz i5",
        memory: "8 GB",
        diskSize: "256 GB",
        chargerType: "30W USB-C",
        chargerIncluded: true,
        condition: "B",
        value: "420",
        soldPrice: "",
        dateDonated: "12/7/21",
        donatedBy: "BetterUP",
        notes: "Kenneth released as of 6/22",
        listPrice: ""
    },
    {
        serial: "FVFWLYJ0J1WL",
        laptopId: "LYJ0",
        status: "READY",
        model: "MacBookAir7,2",
        screenSize: "13\"",
        cpuType: "1.80GHz i5",
        memory: "8 GB",
        diskSize: "256 GB",
        chargerType: "45W MagSafe 2",
        chargerIncluded: false,
        condition: "C",
        value: "370",
        soldPrice: "",
        dateDonated: "7/26/21",
        donatedBy: "BetterUP",
        notes: "Unlock Code 123456 Released 10/12/2021",
        listPrice: ""
    },
    {
        serial: "FVFX32K7J1WL",
        laptopId: "32K7",
        status: "READY",
        model: "MacBookAir7,2",
        screenSize: "13\"",
        cpuType: "1.80GHz i5",
        memory: "8 GB",
        diskSize: "256 GB",
        chargerType: "45W MagSafe 2",
        chargerIncluded: false,
        condition: "A",
        value: "370",
        soldPrice: "",
        dateDonated: "7/26/21",
        donatedBy: "BetterUP",
        notes: "",
        listPrice: ""
    },
    {
        serial: "C02Y410AJK78",
        laptopId: "410A",
        status: "READY",
        model: "MacBookAir8,1",
        screenSize: "13\"",
        cpuType: "1.60GHz i5",
        memory: "8 GB",
        diskSize: "256 GB",
        chargerType: "30W USB-C",
        chargerIncluded: false,
        condition: "A",
        value: "420",
        soldPrice: "",
        dateDonated: "9/3/21",
        donatedBy: "BetterUP",
        notes: "",
        listPrice: ""
    },
    {
        serial: "C02Y52VHJK78",
        laptopId: "52VH",
        status: "READY",
        model: "MacBookAir8,1",
        screenSize: "13\"",
        cpuType: "1.60GHz i5",
        memory: "8 GB",
        diskSize: "256 GB",
        chargerType: "30W USB-C",
        chargerIncluded: false,
        condition: "B",
        value: "420",
        soldPrice: "",
        dateDonated: "9/3/21",
        donatedBy: "BetterUP",
        notes: "",
        listPrice: ""
    },
    {
        serial: "C02Y21P5JK78",
        laptopId: "21P5",
        status: "READY",
        model: "MacBookAir8,1",
        screenSize: "13\"",
        cpuType: "1.60GHz i5",
        memory: "8 GB",
        diskSize: "256 GB",
        chargerType: "30W USB-C",
        chargerIncluded: true,
        condition: "A",
        value: "420",
        soldPrice: "",
        dateDonated: "9/14/21",
        donatedBy: "BetterUP",
        notes: "",
        listPrice: ""
    },
    {
        serial: "C02Y26D5JK78",
        laptopId: "26D5",
        status: "READY",
        model: "MacBookAir8,1",
        screenSize: "13\"",
        cpuType: "1.60GHz i5",
        memory: "8 GB",
        diskSize: "256 GB",
        chargerType: "30W USB-C",
        chargerIncluded: true,
        condition: "B",
        value: "420",
        soldPrice: "",
        dateDonated: "10/27/21",
        donatedBy: "BetterUP",
        notes: "",
        listPrice: ""
    },
    {
        serial: "C02FVBHQQ05N",
        laptopId: "VBHQ",
        status: "READY",
        model: "MacbbookPro",
        screenSize: "13\"",
        cpuType: "3.2GHz",
        memory: "8 GB",
        diskSize: "256 GB",
        chargerType: "52.8W",
        chargerIncluded: false,
        condition: "A",
        value: "410",
        soldPrice: "",
        dateDonated: "",
        donatedBy: "BetterUP",
        notes: "Kenneth released as of 6/22",
        listPrice: ""
    },
    {
        serial: "C02MF3UCF6T6",
        laptopId: "F3UC",
        status: "READY",
        model: "MacBook Air",
        screenSize: "13\"",
        cpuType: "1.7GHz",
        memory: "8 GB",
        diskSize: "256 GB",
        chargerType: "",
        chargerIncluded: false,
        condition: "B",
        value: "50",
        soldPrice: "",
        dateDonated: "",
        donatedBy: "BetterUP",
        notes: "",
        listPrice: ""
    },
    {
        serial: "C02Z27JQLYWG",
        laptopId: "27JQ",
        status: "RECYCLE",
        model: "MacBook Air",
        screenSize: "13\"",
        cpuType: "1.6GHz",
        memory: "8 GB",
        diskSize: "256 GB",
        chargerType: "30W USB-C",
        chargerIncluded: false,
        condition: "A",
        value: "285",
        soldPrice: "",
        dateDonated: "",
        donatedBy: "BetterUP",
        notes: "Recycle - Blocked and cannot be released",
        listPrice: ""
    },
    {
        serial: "FVFWL2MPJ1WL",
        laptopId: "L2MP",
        status: "RECYCLE",
        model: "MacBookAir7,2",
        screenSize: "13\"",
        cpuType: "1.80GHz i5",
        memory: "8 GB",
        diskSize: "256 GB",
        chargerType: "45W MagSafe 2",
        chargerIncluded: false,
        condition: "B",
        value: "370",
        soldPrice: "",
        dateDonated: "7/26/21",
        donatedBy: "BetterUP",
        notes: "Won't turn on? (note: we had this listed previously, but volunteer marked it as blocked, might still work? need to test)",
        listPrice: ""
    },
    {
        serial: "FVFYVD38LYWJ",
        laptopId: "VD38",
        status: "RECYCLE",
        model: "MacBook Air",
        screenSize: "13\"",
        cpuType: "1.6GHz i5",
        memory: "8 GB",
        diskSize: "256 GB",
        chargerType: "30W USB-C",
        chargerIncluded: false,
        condition: "B or C",
        value: "55",
        soldPrice: "",
        dateDonated: "",
        donatedBy: "BetterUP",
        notes: "VERY dirty, needs cleaning",
        listPrice: ""
    },
    {
        serial: "C02Y26FHJK78",
        laptopId: "26FH",
        status: "RECYCLE",
        model: "MacBook Air",
        screenSize: "13\"",
        cpuType: "1.6GHz",
        memory: "8 GB",
        diskSize: "256 GB",
        chargerType: "30W USB-C",
        chargerIncluded: false,
        condition: "A",
        value: "270",
        soldPrice: "",
        dateDonated: "",
        donatedBy: "BetterUP",
        notes: "BLOCKED - Unable to release",
        listPrice: ""
    },
    {
        serial: "FVFYVETBLYWJ",
        laptopId: "VETB",
        status: "RECYCLE",
        model: "MacBook Air",
        screenSize: "13\"",
        cpuType: "1.6GHz i5",
        memory: "8 GB",
        diskSize: "256 GB",
        chargerType: "30W USB-C",
        chargerIncluded: false,
        condition: "A",
        value: "285",
        soldPrice: "",
        dateDonated: "",
        donatedBy: "BetterUP",
        notes: "Locked - cannot be released",
        listPrice: ""
    },
    {
        serial: "C02XJ0K8JK7G",
        laptopId: "J0K8",
        status: "RECYCLE",
        model: "MacBook Air",
        screenSize: "13\"",
        cpuType: "1.6 GHz i5",
        memory: "8 GB",
        diskSize: "256 GB",
        chargerType: "30W USB-C",
        chargerIncluded: false,
        condition: "B",
        value: "55",
        soldPrice: "",
        dateDonated: "",
        donatedBy: "BetterUP",
        notes: "Recycle - trackpad malfunctioning",
        listPrice: ""
    },
    {
        serial: "C02CK58WP3XY",
        laptopId: "K58W",
        status: "SOLD",
        model: "MacBookPro16,3",
        screenSize: "13\"",
        cpuType: "1.4GHz i5",
        memory: "8 GB",
        diskSize: "256 GB",
        chargerType: "61W USB-C",
        chargerIncluded: true,
        condition: "B",
        value: "600",
        soldPrice: "",
        dateDonated: "9/3/21",
        donatedBy: "BetterUP",
        notes: "Sold to Blue Label Labs",
        listPrice: ""
    },
    {
        serial: "FVFC81P3LYWP",
        laptopId: "81P3",
        status: "SOLD",
        model: "MacBookAir8,2",
        screenSize: "13\"",
        cpuType: "1.60GHz i5",
        memory: "8 GB",
        diskSize: "256 GB",
        chargerType: "30W USB-C",
        chargerIncluded: true,
        condition: "A",
        value: "480",
        soldPrice: "",
        dateDonated: "7/26/21",
        donatedBy: "BetterUP",
        notes: "Sold to Amy C.",
        listPrice: ""
    },
    {
        serial: "FVFC41J7L413",
        laptopId: "41J7",
        status: "DONATED",
        model: "MacBookPro15,4",
        screenSize: "13\"",
        cpuType: "1.4GHz i5",
        memory: "16 GB",
        diskSize: "256 GB",
        chargerType: "61W USB-C",
        chargerIncluded: true,
        condition: "B",
        value: "560",
        soldPrice: "",
        dateDonated: "9/3/21",
        donatedBy: "BetterUP",
        notes: "Released (10/12/2021)",
        listPrice: ""
    },
    {
        serial: "C02YT8AQLVCF",
        laptopId: "T8AQ",
        status: "READY",
        model: "MacBook Pro",
        screenSize: "15\"",
        cpuType: "2.6GHz Core i7",
        memory: "16 GB",
        diskSize: "256 GB",
        chargerType: "87W USB-C",
        chargerIncluded: false,
        condition: "A",
        value: "310",
        soldPrice: "",
        dateDonated: "",
        donatedBy: "BetterUP",
        notes: "",
        listPrice: ""
    },
    {
        serial: "",
        laptopId: "",
        status: "READY",
        model: "MacBookPro15,1",
        screenSize: "15\"",
        cpuType: "2.6GHz i7",
        memory: "16 GB",
        diskSize: "256 GB",
        chargerType: "87W USB-C",
        chargerIncluded: true,
        condition: "B",
        value: "940",
        soldPrice: "",
        dateDonated: "7/26/21",
        donatedBy: "BetterUP",
        notes: "",
        listPrice: ""
    },
    {
        serial: "C02YV7CTLVCF",
        laptopId: "V7CT",
        status: "READY",
        model: "MacBookPro15,1",
        screenSize: "15\"",
        cpuType: "2.6GHz i7",
        memory: "16 GB",
        diskSize: "256 GB",
        chargerType: "87W USB-C",
        chargerIncluded: true,
        condition: "B",
        value: "940",
        soldPrice: "",
        dateDonated: "8/30/21",
        donatedBy: "BetterUP",
        notes: "",
        listPrice: ""
    },
    {
        serial: "C02CD2WSM6KG",
        laptopId: "D2WS",
        status: "READY",
        model: "MacBookAir9,1",
        screenSize: "13\"",
        cpuType: "1.10GHz i5",
        memory: "8 GB",
        diskSize: "512 GB",
        chargerType: "30W USB-C",
        chargerIncluded: false,
        condition: "A",
        value: "550",
        soldPrice: "",
        dateDonated: "9/3/21",
        donatedBy: "BetterUP",
        notes: "",
        listPrice: ""
    },
    {
        serial: "C02F94UAQ05N",
        laptopId: "94UA",
        status: "RECYCLE",
        model: "MacBookPro 13\"",
        screenSize: "13\"",
        cpuType: "3.2 GHz M1",
        memory: "8 GB",
        diskSize: "512 GB",
        chargerType: "61W USB-C",
        chargerIncluded: true,
        condition: "A",
        value: "430",
        soldPrice: "",
        dateDonated: "",
        donatedBy: "BetterUP",
        notes: "BLOCKED - Unable to release",
        listPrice: ""
    },
    {
        serial: "C02DWACWQ05N",
        laptopId: "WACW",
        status: "INTERNAL",
        model: "MacBookPro17,1",
        screenSize: "13\"",
        cpuType: "M1 3.2GHz",
        memory: "16 GB",
        diskSize: "512 GB",
        chargerType: "61W USB-C",
        chargerIncluded: true,
        condition: "A",
        value: "740",
        soldPrice: "",
        dateDonated: "7/22/21",
        donatedBy: "BetterUP",
        notes: "Lorene's laptop",
        listPrice: ""
    },
    {
        serial: "C02G730JQ05N",
        laptopId: "730J",
        status: "INTERNAL",
        model: "MacBookPro17,1",
        screenSize: "13\"",
        cpuType: "M1 3.2GHz",
        memory: "16 GB",
        diskSize: "512 GB",
        chargerType: "61W USB-C",
        chargerIncluded: true,
        condition: "A",
        value: "740",
        soldPrice: "",
        dateDonated: "12/8/21",
        donatedBy: "BetterUP",
        notes: "Sheridan's laptop",
        listPrice: ""
    },
    {
        serial: "C02DV498ML7L",
        laptopId: "V498",
        status: "READY",
        model: "MacBookPro16,2",
        screenSize: "13\"",
        cpuType: "2GHz i5",
        memory: "16 GB",
        diskSize: "512 GB",
        chargerType: "61W USB-C",
        chargerIncluded: true,
        condition: "A",
        value: "630",
        soldPrice: "",
        dateDonated: "1/19/22",
        donatedBy: "BetterUP",
        notes: "Kenneth released as of 6/22",
        listPrice: ""
    },
    {
        serial: "C02D80AZML7H",
        laptopId: "80AZ",
        status: "READY",
        model: "MacBookPro16,2",
        screenSize: "13\"",
        cpuType: "2.0GHz i5",
        memory: "16 GB",
        diskSize: "512 GB",
        chargerType: "61W USB-C",
        chargerIncluded: true,
        condition: "A",
        value: "630",
        soldPrice: "",
        dateDonated: "9/2/21",
        donatedBy: "BetterUP",
        notes: "",
        listPrice: ""
    },
    {
        serial: "C02FW8LLQ05N",
        laptopId: "W8LL",
        status: "RECYCLE",
        model: "MacBookPro17,1",
        screenSize: "13\"",
        cpuType: "M1 3.2GHz",
        memory: "16 GB",
        diskSize: "512 GB",
        chargerType: "61W USB-C",
        chargerIncluded: true,
        condition: "A",
        value: "740",
        soldPrice: "",
        dateDonated: "12/8/21",
        donatedBy: "BetterUP",
        notes: "System lock pin code required",
        listPrice: ""
    },
    {
        serial: "C02FD2WQQ05N",
        laptopId: "D2WQ",
        status: "SOLD",
        model: "MacBookPro17,1",
        screenSize: "13\"",
        cpuType: "M1 3.2GHz",
        memory: "16 GB",
        diskSize: "512 GB",
        chargerType: "61W USB-C",
        chargerIncluded: true,
        condition: "A",
        value: "740",
        soldPrice: "1184",
        dateDonated: "8/25/21",
        donatedBy: "BetterUP",
        notes: "Sold to Joel Monahan, Prarie Health & Welness",
        listPrice: ""
    },
    {
        serial: "C02F94SPQ05N",
        laptopId: "94SP",
        status: "SOLD",
        model: "MacBookPro17,1",
        screenSize: "13\"",
        cpuType: "M1 3.2GHz",
        memory: "16 GB",
        diskSize: "512 GB",
        chargerType: "61W USB-C",
        chargerIncluded: true,
        condition: "A",
        value: "740",
        soldPrice: "1000",
        dateDonated: "8/30/21",
        donatedBy: "BetterUP",
        notes: "Sold to Parth Patel",
        listPrice: ""
    },
    {
        serial: "C02F94U8Q05N",
        laptopId: "94U8",
        status: "SOLD",
        model: "MacBookPro17,1",
        screenSize: "13\"",
        cpuType: "M1 3.2GHz",
        memory: "16 GB",
        diskSize: "512 GB",
        chargerType: "61W USB-C",
        chargerIncluded: true,
        condition: "A",
        value: "740",
        soldPrice: "1000",
        dateDonated: "9/14/21",
        donatedBy: "BetterUP",
        notes: "Sold to Parth Patel",
        listPrice: ""
    },
    {
        serial: "C02DWA1KQ05N",
        laptopId: "WA1K",
        status: "SOLD",
        model: "MacBookPro17,1",
        screenSize: "13\"",
        cpuType: "M1 3.2GHz",
        memory: "16 GB",
        diskSize: "512 GB",
        chargerType: "61W USB-C",
        chargerIncluded: true,
        condition: "A",
        value: "740",
        soldPrice: "1184",
        dateDonated: "9/16/21",
        donatedBy: "BetterUP",
        notes: "Sold to Joel Monahan, Prarie Health & Welness",
        listPrice: ""
    },
    {
        serial: "C02FM404Q05N",
        laptopId: "M404",
        status: "SOLD",
        model: "MacBookPro17,1",
        screenSize: "13\"",
        cpuType: "M1 3.2GHz",
        memory: "16 GB",
        diskSize: "512 GB",
        chargerType: "61W USB-C",
        chargerIncluded: true,
        condition: "A",
        value: "740",
        soldPrice: "1110",
        dateDonated: "10/15/21",
        donatedBy: "BetterUP",
        notes: "Sold to Chai Quán",
        listPrice: ""
    },
    {
        serial: "C02F8057Q05N",
        laptopId: "8057",
        status: "SOLD",
        model: "MacBookPro17,1",
        screenSize: "13\"",
        cpuType: "M1 3.2GHz",
        memory: "16 GB",
        diskSize: "512 GB",
        chargerType: "61W-USB-C",
        chargerIncluded: true,
        condition: "A",
        value: "740",
        soldPrice: "1184",
        dateDonated: "10/29/21",
        donatedBy: "BetterUP",
        notes: "Sold to Taryn Hill (Check)",
        listPrice: ""
    },
    {
        serial: "C02F806JQ05N",
        laptopId: "806J",
        status: "SOLD",
        model: "MacBookPro17,1",
        screenSize: "13\"",
        cpuType: "M1 3.2GHz",
        memory: "16 GB",
        diskSize: "512 GB",
        chargerType: "61W USB-C",
        chargerIncluded: true,
        condition: "A",
        value: "740",
        soldPrice: "1184",
        dateDonated: "11/2/21",
        donatedBy: "BetterUP",
        notes: "Sold to Cody",
        listPrice: ""
    },
    {
        serial: "C02G72W1Q05N",
        laptopId: "72W1",
        status: "SOLD",
        model: "MacBookPro17,1",
        screenSize: "13\"",
        cpuType: "M1 3.2GHz",
        memory: "16 GB",
        diskSize: "512 GB",
        chargerType: "61W USB-C",
        chargerIncluded: true,
        condition: "A",
        value: "740",
        soldPrice: "1184",
        dateDonated: "11/29/21",
        donatedBy: "BetterUP",
        notes: "Sold to Paul Davis",
        listPrice: ""
    },
    {
        serial: "C02W3B6MHTD6",
        laptopId: "3B6M",
        status: "READY",
        model: "MacBookPro14,3",
        screenSize: "15\"",
        cpuType: "2.8GHz i7",
        memory: "16 GB",
        diskSize: "512 GB",
        chargerType: "87W USB-C",
        chargerIncluded: true,
        condition: "B",
        value: "750",
        soldPrice: "",
        dateDonated: "10/26/21",
        donatedBy: "BetterUP",
        notes: "",
        listPrice: ""
    },
    {
        serial: "C02VD9NTHTD6",
        laptopId: "D9NT",
        status: "RECYCLE",
        model: "MacBookPro14,3",
        screenSize: "15\"",
        cpuType: "2.8GHz i7",
        memory: "16 GB",
        diskSize: "512 GB",
        chargerType: "87W USB-C",
        chargerIncluded: false,
        condition: "A",
        value: "280",
        soldPrice: "",
        dateDonated: "",
        donatedBy: "BetterUP",
        notes: "Getting \"UNTRUSTED_CERT_TITLE\" error when trying to reinstall",
        listPrice: ""
    },
    {
        serial: "C02CM42KMD6M",
        laptopId: "M42K",
        status: "READY",
        model: "MacBook Pro",
        screenSize: "16\"",
        cpuType: "2.6 GHz i7",
        memory: "16 GB",
        diskSize: "512 GB",
        chargerType: "96W USB-C",
        chargerIncluded: false,
        condition: "A",
        value: "420",
        soldPrice: "",
        dateDonated: "",
        donatedBy: "BetterUP",
        notes: "Kenneth released as of 6/22",
        listPrice: ""
    },
    {
        serial: "C02ZJD6VMD6M",
        laptopId: "JD6V",
        status: "READY",
        model: "MacBookPro16,1",
        screenSize: "16\"",
        cpuType: "2.6 GHz i7",
        memory: "16 GB",
        diskSize: "512 GB",
        chargerType: "96W USB-C",
        chargerIncluded: true,
        condition: "A",
        value: "1160",
        soldPrice: "",
        dateDonated: "12/8/21",
        donatedBy: "BetterUP",
        notes: "",
        listPrice: ""
    },
    {
        serial: "C02DD3CNMD6P",
        laptopId: "D3CN",
        status: "RECYCLE",
        model: "MacBook Pro",
        screenSize: "16\"",
        cpuType: "2.6 GHz i7",
        memory: "16 GB",
        diskSize: "512 GB",
        chargerType: "96 W USB-C",
        chargerIncluded: false,
        condition: "A",
        value: "420",
        soldPrice: "",
        dateDonated: "",
        donatedBy: "BetterUP",
        notes: "Getting error message",
        listPrice: ""
    },
    {
        serial: "C02CC0U1M6KH",
        laptopId: "C0U1",
        status: "DONATED",
        model: "MacBookAir9,1",
        screenSize: "13\"",
        cpuType: "1.1GHz i5",
        memory: "8 GB",
        diskSize: "512 GB",
        chargerType: "30W USB-C",
        chargerIncluded: false,
        condition: "A",
        value: "550",
        soldPrice: "",
        dateDonated: "7/26/21",
        donatedBy: "BetterUP",
        notes: "Released (10/12/2021)",
        listPrice: ""
    },
    {
        serial: "FVFCN3Z5M6KK",
        laptopId: "N3Z5",
        status: "RECYCLE",
        model: "MacBook Air",
        screenSize: "13\"",
        cpuType: "1.2 GHz i7",
        memory: "8 GB",
        diskSize: "512 GB",
        chargerType: "30W USB-C",
        chargerIncluded: false,
        condition: "A",
        value: "285",
        soldPrice: "",
        dateDonated: "",
        donatedBy: "BetterUP",
        notes: "System lock pin code required - cannot be released",
        listPrice: ""
    },
    {
        serial: "C02FK2NWMD6T",
        laptopId: "K2NW",
        status: "READY",
        model: "MacBookPro16,1",
        screenSize: "16\"",
        cpuType: "2.4GHz",
        memory: "32 GB",
        diskSize: "1024 GB",
        chargerType: "96W USB-C",
        chargerIncluded: true,
        condition: "A",
        value: "1210",
        soldPrice: "",
        dateDonated: "10/6/21",
        donatedBy: "BetterUP",
        notes: "",
        listPrice: ""
    },
    {
        serial: "C02DD0DLMD6W",
        laptopId: "D0DL",
        status: "READY",
        model: "MacBookPro16,1",
        screenSize: "16\"",
        cpuType: "2.4GHz",
        memory: "32 GB",
        diskSize: "1024 GB",
        chargerType: "96W USB-C",
        chargerIncluded: true,
        condition: "A",
        value: "1210",
        soldPrice: "",
        dateDonated: "10/27/21",
        donatedBy: "BetterUP",
        notes: "",
        listPrice: ""
    },
    {
        serial: "C02DX1BKMD6R",
        laptopId: "X1BK",
        status: "READY",
        model: "MacBookPro16,1",
        screenSize: "16\"",
        cpuType: "2.4GHz",
        memory: "32 GB",
        diskSize: "1024 GB",
        chargerType: "96W USB-C",
        chargerIncluded: false,
        condition: "A",
        value: "1210",
        soldPrice: "",
        dateDonated: "10/27/21",
        donatedBy: "BetterUP",
        notes: "",
        listPrice: ""
    },
    {
        serial: "C02F32C4MD6T",
        laptopId: "32C4",
        status: "RECYCLE",
        model: "MacBookPro16,1",
        screenSize: "16\"",
        cpuType: "2.4GHz i9",
        memory: "32 GB",
        diskSize: "1024 GB",
        chargerType: "96W USB-C",
        chargerIncluded: false,
        condition: "B",
        value: "1210",
        soldPrice: "",
        dateDonated: "9/30/21",
        donatedBy: "BetterUP",
        notes: "Stuck in boot loop - network recovery",
        listPrice: ""
    },
    {
        serial: "C02Y30G1JK78",
        laptopId: "30G1",
        status: "READY (need specs)",
        model: "MacBookAir8,1",
        screenSize: "13\"",
        cpuType: "1.6GHz i5",
        memory: "8 GB",
        diskSize: "?",
        chargerType: "",
        chargerIncluded: "",
        condition: "",
        value: "",
        soldPrice: "",
        dateDonated: "",
        donatedBy: "BetterUP",
        notes: "",
        listPrice: ""
    },
    {
        serial: "FVFXD077JK77",
        laptopId: "D077",
        status: "READY (need specs)",
        model: "MacBookAir8,1",
        screenSize: "13\"",
        cpuType: "1.6GHz i5",
        memory: "8 GB",
        diskSize: "?",
        chargerType: "",
        chargerIncluded: "",
        condition: "A",
        value: "",
        soldPrice: "",
        dateDonated: "",
        donatedBy: "BetterUP",
        notes: "",
        listPrice: ""
    },
    {
        serial: "C02XG15HHH21",
        laptopId: "G15H",
        status: "RECYCLE",
        model: "MacBook",
        screenSize: "12\"",
        cpuType: "?",
        memory: "?",
        diskSize: "?",
        chargerType: "29W USB-C",
        chargerIncluded: false,
        condition: "A",
        value: "130",
        soldPrice: "",
        dateDonated: "",
        donatedBy: "BetterUP",
        notes: "",
        listPrice: ""
    },
    {
        serial: "C02XK03MJHD3",
        laptopId: "K03M",
        status: "READY (need specs)",
        model: "MacBookPro15,2",
        screenSize: "13\"",
        cpuType: "?",
        memory: "?",
        diskSize: "?",
        chargerType: "61W USB-C",
        chargerIncluded: true,
        condition: "A",
        value: "425",
        soldPrice: "",
        dateDonated: "4/7/22",
        donatedBy: "BetterUP",
        notes: "",
        listPrice: ""
    },
    {
        serial: "C02FM42MQ05N",
        laptopId: "M42M",
        status: "RECYCLE",
        model: "MacBookPro17,1",
        screenSize: "13\"",
        cpuType: "M1 3.2GHz",
        memory: "?",
        diskSize: "?",
        chargerType: "61W USB-C",
        chargerIncluded: true,
        condition: "A",
        value: "740",
        soldPrice: "",
        dateDonated: "1/20/22",
        donatedBy: "BetterUP",
        notes: "",
        listPrice: ""
    },
    {
        serial: "C02Z27JZLYWG",
        laptopId: "27JZ",
        status: "RECYCLE",
        model: "MacBookAir8,2",
        screenSize: "13\"",
        cpuType: "?",
        memory: "?",
        diskSize: "?",
        chargerType: "61W USB-C",
        chargerIncluded: true,
        condition: "A",
        value: "450",
        soldPrice: "",
        dateDonated: "1/24/22",
        donatedBy: "BetterUP",
        notes: "System lock pin code required",
        listPrice: ""
    },
    {
        serial: "C02Y3B30JG5J",
        laptopId: "3B30",
        status: "UNPROCESSED",
        model: "?",
        screenSize: "15\"",
        cpuType: "?",
        memory: "?",
        diskSize: "?",
        chargerType: "87W USB-C",
        chargerIncluded: true,
        condition: "A",
        value: "800",
        soldPrice: "",
        dateDonated: "3/16/22",
        donatedBy: "BetterUP",
        notes: "",
        listPrice: ""
    },
    {
        serial: "C02FK356MD6T",
        laptopId: "K356",
        status: "READY (need specs)",
        model: "MacBookPro16,1",
        screenSize: "16\"",
        cpuType: "?",
        memory: "?",
        diskSize: "?",
        chargerType: "96W USB-C",
        chargerIncluded: false,
        condition: "B",
        value: "1210",
        soldPrice: "",
        dateDonated: "11/8/21",
        donatedBy: "BetterUP",
        notes: "",
        listPrice: ""
    },
    {
        serial: "C02FX338MD6R",
        laptopId: "X338",
        status: "RECYCLE",
        model: "MacBook Pro",
        screenSize: "16\"",
        cpuType: "?",
        memory: "?",
        diskSize: "?",
        chargerType: "87W USB-C",
        chargerIncluded: true,
        condition: "A",
        value: "440",
        soldPrice: "",
        dateDonated: "",
        donatedBy: "BetterUP",
        notes: "",
        listPrice: ""
    },
    {
        serial: "C02FX0XPMD6R",
        laptopId: "X0XP",
        status: "RECYCLE",
        model: "MacBook Pro",
        screenSize: "16\"",
        cpuType: "?",
        memory: "?",
        diskSize: "?",
        chargerType: "87W USB-C",
        chargerIncluded: false,
        condition: "A",
        value: "440",
        soldPrice: "",
        dateDonated: "",
        donatedBy: "BetterUP",
        notes: "",
        listPrice: ""
    },
    {
        serial: "C02ZJ0JDLVDT",
        laptopId: "J0JD",
        status: "READY (need specs)",
        model: "MacBookPro15,1",
        screenSize: "15\"",
        cpuType: "",
        memory: "",
        diskSize: "?",
        chargerType: "",
        chargerIncluded: "",
        condition: "",
        value: "",
        soldPrice: "",
        dateDonated: "",
        donatedBy: "BetterUP",
        notes: "",
        listPrice: ""
    },
    {
        serial: "FVFC60QRLYWN",
        laptopId: "60QR",
        status: "RECYCLE",
        model: "MacBookAir8,2",
        screenSize: "16\"",
        cpuType: "1.6 GHz Core i5",
        memory: "8 GB",
        diskSize: "128 GB",
        chargerType: "30W USB-C",
        chargerIncluded: false,
        condition: "A",
        value: "285",
        soldPrice: "",
        dateDonated: "7/1/22",
        donatedBy: "BetterUP",
        notes: "",
        listPrice: ""
    },
    {
        serial: "C02F54WRMD6R",
        laptopId: "54WR",
        status: "RECYCLE",
        model: "MacBook Pro",
        screenSize: "16\"",
        cpuType: "2.3GHz",
        memory: "16 GB",
        diskSize: "1 T",
        chargerType: "87W USB-C",
        chargerIncluded: true,
        condition: "A",
        value: "440",
        soldPrice: "",
        dateDonated: "",
        donatedBy: "BetterUP",
        notes: "",
        listPrice: ""
    },
    {
        serial: "C02DX1BLMD6R",
        laptopId: "X1BL",
        status: "REINSTALL",
        model: "MacBookPro16,1",
        screenSize: "16\"",
        cpuType: "2.4 GHz i9",
        memory: "32 GB",
        diskSize: "1 T",
        chargerType: "96W USB-C",
        chargerIncluded: false,
        condition: "A",
        value: "1210",
        soldPrice: "",
        dateDonated: "1/27/22",
        donatedBy: "BetterUP",
        notes: "Kenneth released as of 6/22",
        listPrice: ""
    },
    {
        serial: "C02YL6Q3LVCF",
        laptopId: "L6Q3",
        status: "READY",
        model: "MacBookPro",
        screenSize: "15\"",
        cpuType: "2.6GHz i7",
        memory: "16 GB",
        diskSize: "256 GB",
        chargerType: "87W USB-C",
        chargerIncluded: true,
        condition: "A",
        value: "800",
        soldPrice: "",
        dateDonated: "3/8/22",
        donatedBy: "BetterUP",
        notes: "",
        listPrice: ""
    },
    {
        serial: "FVFWLU1TJ1WL",
        laptopId: "LU1T",
        status: "RECYCLE",
        model: "MacBook Air",
        screenSize: "13\"",
        cpuType: "1.8 GHz",
        memory: "8 GB",
        diskSize: "256 GB",
        chargerType: "45W MagSafe",
        chargerIncluded: false,
        condition: "A",
        value: "170",
        soldPrice: "",
        dateDonated: "",
        donatedBy: "BetterUP",
        notes: "Blocked and cannot be released",
        listPrice: ""
    },
    {
        serial: "C02CPLW2MD6M",
        laptopId: "PLW2",
        status: "DONATED",
        model: "MacBookPro16,1",
        screenSize: "16\"",
        cpuType: "2.6 GHz",
        memory: "16 GB",
        diskSize: "512 GB",
        chargerType: "96W USB-C",
        chargerIncluded: false,
        condition: "A",
        value: "420",
        soldPrice: "",
        dateDonated: "",
        donatedBy: "BetterUP",
        notes: "",
        listPrice: ""
    },
    {
        serial: "C02C13MBMD6M",
        laptopId: "13MB",
        status: "UNPROCESSED",
        model: "MacBookPro16,1",
        screenSize: "16\"",
        cpuType: "2.6GHz i7",
        memory: "16 GB",
        diskSize: "512 GB",
        chargerType: "96W USB-C",
        chargerIncluded: true,
        condition: "A",
        value: "385",
        soldPrice: "",
        dateDonated: "6/29/22",
        donatedBy: "BetterUP",
        notes: "",
        listPrice: ""
    },
    {
        serial: "JCN0CV05D63350E",
        laptopId: "",
        status: "",
        model: "ASUS Zenbook 14 UX433",
        screenSize: "",
        cpuType: "1.8 GHz Core i7",
        memory: "16 GB",
        diskSize: "512 GB",
        chargerType: "",
        chargerIncluded: "",
        condition: "",
        value: "",
        soldPrice: "",
        dateDonated: "",
        donatedBy: "BetterUP",
        notes: "",
        listPrice: ""
    },
    {
        serial: "FVFC41J7L413",
        laptopId: "41J7",
        status: "READY",
        model: "MacBook Pro",
        screenSize: "13\"",
        cpuType: "1.4 GHz Quad-Core Intel i5",
        memory: "16 GB",
        diskSize: "",
        chargerType: "61W USB-C",
        chargerIncluded: false,
        condition: "A",
        value: "310",
        soldPrice: "",
        dateDonated: "",
        donatedBy: "BetterUP",
        notes: "",
        listPrice: ""
    },
    {
        serial: "C02F94VHQ05N",
        laptopId: "94VH",
        status: "UNPROCESSED",
        model: "MacBookPro17,1",
        screenSize: "13\"",
        cpuType: "M1 3.2GHz",
        memory: "?",
        diskSize: "",
        chargerType: "61W USB-C",
        chargerIncluded: true,
        condition: "A",
        value: "740",
        soldPrice: "",
        dateDonated: "1/24/22",
        donatedBy: "BetterUP",
        notes: "",
        listPrice: ""
    },
    {
        serial: "C02WH0CQHV2R",
        laptopId: "H0CQ",
        status: "DONATED",
        model: "MacBookPro14,2",
        screenSize: "13\"",
        cpuType: "",
        memory: "",
        diskSize: "",
        chargerType: "61W USB-C",
        chargerIncluded: false,
        condition: "B",
        value: "410",
        soldPrice: "",
        dateDonated: "7/26/21",
        donatedBy: "BetterUP",
        notes: "Donated - Kihanna Woods",
        listPrice: ""
    },
    {
        serial: "C02F94SRQ05N",
        laptopId: "94SR",
        status: "INTERNAL",
        model: "MacBookPro17,1",
        screenSize: "13\"",
        cpuType: "",
        memory: "",
        diskSize: "",
        chargerType: "",
        chargerIncluded: true,
        condition: "",
        value: "740",
        soldPrice: "",
        dateDonated: "12/14/21",
        donatedBy: "BetterUP",
        notes: "Yaw's laptop",
        listPrice: ""
    },
    {
        serial: "C02FM41TQ05N",
        laptopId: "M41T",
        status: "RECYCLE",
        model: "MacBookPro17,1",
        screenSize: "13\"",
        cpuType: "",
        memory: "",
        diskSize: "",
        chargerType: "",
        chargerIncluded: true,
        condition: "",
        value: "740",
        soldPrice: "",
        dateDonated: "12/14/21",
        donatedBy: "BetterUP",
        notes: "System lock pin code required",
        listPrice: ""
    },
    {
        serial: "C02QR8R3G8WN",
        laptopId: "R8R3",
        status: "RECYCLE",
        model: "MacBookPro11,4",
        screenSize: "15\"",
        cpuType: "",
        memory: "",
        diskSize: "",
        chargerType: "85W MagSafe 2",
        chargerIncluded: true,
        condition: "C",
        value: "440",
        soldPrice: "",
        dateDonated: "8/30/21",
        donatedBy: "BetterUP",
        notes: "System lock pin code",
        listPrice: ""
    },
    {
        serial: "C02FD5GMMD6R",
        laptopId: "D5GM",
        status: "RECYCLE",
        model: "MacBookPro16,1",
        screenSize: "16\"",
        cpuType: "",
        memory: "",
        diskSize: "",
        chargerType: "96W USB-C",
        chargerIncluded: false,
        condition: "A",
        value: "1210",
        soldPrice: "",
        dateDonated: "9/1/21",
        donatedBy: "BetterUP",
        notes: "System lock pin code - Released (10/12/2021)",
        listPrice: ""
    },
    {
        serial: "C02NCDSGG3QJ",
        laptopId: "CDSG",
        status: "Donated",
        model: "MacBookPro11,1",
        screenSize: "",
        cpuType: "Core i5 2.6GHz",
        memory: "8 GB",
        diskSize: "256 GB",
        chargerType: "60W MagSafe 2",
        chargerIncluded: "Y",
        condition: "B",
        value: "260",
        soldPrice: "",
        dateDonated: "11/2/21",
        notes: "Donated - Teryn Washington",
        listPrice: "",
        donatedBy: "OrderMyGear"
    },
    {
        serial: "C02QDC3NFVH5",
        laptopId: "DC3N",
        status: "Donated",
        model: "MacBookPro12,1",
        screenSize: "",
        cpuType: "Core i5 2.7GHz",
        memory: "8 GB",
        diskSize: "256 GB",
        chargerType: "60W MagSafe 2",
        chargerIncluded: "Y",
        condition: "B",
        value: "110",
        soldPrice: "",
        dateDonated: "11/2/21",
        notes: "Donated - Moriah Sanchez",
        listPrice: "",
        donatedBy: "OrderMyGear"
    },
    {
        serial: "C02RGQ6LFVH5",
        laptopId: "GQ6L",
        status: "Donated",
        model: "MacBookPro12,1",
        screenSize: "",
        cpuType: "Core i5 2.7GHz",
        memory: "8 GB",
        diskSize: "256 GB",
        chargerType: "60W MagSafe 2",
        chargerIncluded: "Y",
        condition: "B",
        value: "300",
        soldPrice: "",
        dateDonated: "11/2/21",
        notes: "Donated - Soraya",
        listPrice: "",
        donatedBy: "OrderMyGear"
    },
    {
        serial: "C17PL1B2FVH5",
        laptopId: "L1B2",
        status: "Donated",
        model: "MacBookPro12,1",
        screenSize: "",
        cpuType: "Core i5 2.7GHz",
        memory: "8 GB",
        diskSize: "256 GB",
        chargerType: "60W MagSafe 2",
        chargerIncluded: "Y",
        condition: "A",
        value: "300",
        soldPrice: "",
        dateDonated: "11/30/21",
        notes: "Donated - Uri",
        listPrice: "",
        donatedBy: "OrderMyGear"
    },
    {
        serial: "C02RN80CFVH5",
        laptopId: "N80C",
        status: "Donated",
        model: "MacBookPro12,1",
        screenSize: "",
        cpuType: "Core i5 2.7GHz",
        memory: "8 GB",
        diskSize: "256 GB",
        chargerType: "60W MagSafe 2",
        chargerIncluded: "Y",
        condition: "B",
        value: "300",
        soldPrice: "",
        dateDonated: "11/2/21",
        notes: "Donated - Madison",
        listPrice: "",
        donatedBy: "OrderMyGear"
    },
    {
        serial: "C17Q4507FVH5",
        laptopId: "4507",
        status: "Donated",
        model: "MacBookPro12,1",
        screenSize: "",
        cpuType: "Core i5 2.7GHz",
        memory: "8 GB",
        diskSize: "256 GB",
        chargerType: "60W MagSafe 2",
        chargerIncluded: "Y",
        condition: "A",
        value: "300",
        soldPrice: "",
        dateDonated: "11/30/21",
        notes: "Reserved for Kaleb",
        listPrice: "",
        donatedBy: "OrderMyGear"
    },
    {
        serial: "C02MM0ZJF6T6",
        laptopId: "M0ZJ",
        status: "Donated",
        model: "MacBookAir6,2",
        screenSize: "",
        cpuType: "Core i7 1.7GHz",
        memory: "8 GB",
        diskSize: "256 GB",
        chargerType: "45W MagSafe 2",
        chargerIncluded: "Y",
        condition: "A",
        value: "220",
        soldPrice: "",
        dateDonated: "11/30/21",
        notes: "Reserved for Hope Bebe",
        listPrice: "",
        donatedBy: "OrderMyGear"
    },
    {
        serial: "C02PJLPMFVH5",
        laptopId: "JLPM",
        status: "Donated",
        model: "MacBookPro12,1",
        screenSize: "",
        cpuType: "Core i5 2.7GHz",
        memory: "8 GB",
        diskSize: "256 GB",
        chargerType: "60W MagSafe 2",
        chargerIncluded: "Y",
        condition: "B",
        value: "300",
        soldPrice: "",
        dateDonated: "11/30/21",
        notes: "Reserved for Fortune Bebe",
        listPrice: "",
        donatedBy: "OrderMyGear"
    },
    {
        serial: "C17Q468WFVH5",
        laptopId: "468W",
        status: "Donated",
        model: "MacBookPro12,1",
        screenSize: "",
        cpuType: "Core i5 2.7GHz",
        memory: "8 GB",
        diskSize: "256 GB",
        chargerType: "60W MagSafe 2",
        chargerIncluded: "Y",
        condition: "B",
        value: "300",
        soldPrice: "",
        dateDonated: "11/30/21",
        notes: "Reserved for Joubran Bebe",
        listPrice: "",
        donatedBy: "OrderMyGear"
    },
    {
        serial: "C02RTGPLFVH5",
        laptopId: "TGPL",
        status: "Donated",
        model: "MacBookPro12,1",
        screenSize: "",
        cpuType: "Core i5 2.7GHz",
        memory: "8 GB",
        diskSize: "256 GB",
        chargerType: "60W MagSafe 2",
        chargerIncluded: "Y",
        condition: "B",
        value: "110",
        soldPrice: "",
        dateDonated: "11/2/21",
        notes: "Reserved for Faith Bebe",
        listPrice: "",
        donatedBy: "OrderMyGear"
    },
    {
        serial: "C02Q3F4MFVH5",
        laptopId: "3F4M",
        status: "",
        model: "MacBookPro12,1",
        screenSize: "",
        cpuType: "Core i5 2.7GHz",
        memory: "8 GB",
        diskSize: "256 GB",
        chargerType: "60W MagSafe 2",
        chargerIncluded: "Y",
        condition: "B",
        value: "300",
        soldPrice: "",
        dateDonated: "11/30/21",
        notes: "",
        listPrice: "",
        donatedBy: "OrderMyGear"
    },
    {
        serial: "C02Q51LGFVH5",
        laptopId: "51LG",
        status: "",
        model: "MacBookPro12,1",
        screenSize: "",
        cpuType: "Core i5 2.7GHz",
        memory: "8 GB",
        diskSize: "256 GB",
        chargerType: "60W MagSafe 2",
        chargerIncluded: "Y",
        condition: "B",
        value: "300",
        soldPrice: "",
        dateDonated: "11/30/21",
        notes: "",
        listPrice: "",
        donatedBy: "OrderMyGear"
    },
    {
        serial: "C027787NFVH3",
        laptopId: "787N",
        status: "",
        model: "MacBookPro12,1",
        screenSize: "",
        cpuType: "Core i5 2.7GHz",
        memory: "8 GB",
        diskSize: "256 GB",
        chargerType: "60W MagSafe 2",
        chargerIncluded: "Y",
        condition: "B",
        value: "300",
        soldPrice: "",
        dateDonated: "11/30/21",
        notes: "",
        listPrice: "",
        donatedBy: "OrderMyGear"
    },
    {
        serial: "C02N94LDG5RP",
        laptopId: "94LD",
        status: "",
        model: "MacBookAir6,2",
        screenSize: "",
        cpuType: "Core i7 1.7GHz",
        memory: "8 GB",
        diskSize: "256 GB",
        chargerType: "60W MagSafe 2",
        chargerIncluded: "N",
        condition: "A",
        value: "220",
        soldPrice: "",
        dateDonated: "11/30/21",
        notes: "",
        listPrice: "",
        donatedBy: "OrderMyGear"
    },
    {
        serial: "C02N94LEG5RP",
        laptopId: "94LE",
        status: "",
        model: "MacBookAir6,2",
        screenSize: "",
        cpuType: "Core i7 1.7GHz",
        memory: "8 GB",
        diskSize: "256 GB",
        chargerType: "60W MagSafe 2",
        chargerIncluded: "N",
        condition: "A",
        value: "220",
        soldPrice: "",
        dateDonated: "11/30/21",
        notes: "",
        listPrice: "",
        donatedBy: "OrderMyGear"
    },
    {
        serial: "C02M9570F6T6",
        laptopId: "9570",
        status: "",
        model: "MacBookAir6,2",
        screenSize: "",
        cpuType: "Core i7 1.7GHz",
        memory: "8 GB",
        diskSize: "256 GB",
        chargerType: "60W MagSafe 2",
        chargerIncluded: "N",
        condition: "C",
        value: "45",
        soldPrice: "",
        dateDonated: "11/30/21",
        notes: "",
        listPrice: "",
        donatedBy: "OrderMyGear"
    },
    {
        serial: "C02M95NWF6T6",
        laptopId: "95NW",
        status: "",
        model: "MacBookAir6,2",
        screenSize: "",
        cpuType: "Core i7 1.7GHz",
        memory: "8 GB",
        diskSize: "256 GB",
        chargerType: "60W MagSafe 2",
        chargerIncluded: "N",
        condition: "A",
        value: "220",
        soldPrice: "",
        dateDonated: "11/30/21",
        notes: "",
        listPrice: "",
        donatedBy: "OrderMyGear"
    },
    {
        serial: "C02MF3UBF6T6",
        laptopId: "F3UB",
        status: "",
        model: "MacBookAir6,2",
        screenSize: "",
        cpuType: "Core i7 1.7GHz",
        memory: "8 GB",
        diskSize: "256 GB",
        chargerType: "60W MagSafe 2",
        chargerIncluded: "N",
        condition: "A",
        value: "220",
        soldPrice: "",
        dateDonated: "11/30/21",
        notes: "",
        listPrice: "",
        donatedBy: "OrderMyGear"
    },
    {
        serial: "C02MF3VCF6T6",
        laptopId: "F3VC",
        status: "",
        model: "MacBookAir6,2",
        screenSize: "",
        cpuType: "Core i7 1.7GHz",
        memory: "8 GB",
        diskSize: "256 GB",
        chargerType: "60W MagSafe 2",
        chargerIncluded: "N",
        condition: "B",
        value: "220",
        soldPrice: "",
        dateDonated: "11/30/21",
        notes: "",
        listPrice: "",
        donatedBy: "OrderMyGear"
    },
    {
        serial: "C02MM0ZHF6T6",
        laptopId: "M0ZH",
        status: "",
        model: "MacBookAir6,2",
        screenSize: "",
        cpuType: "Core i7 1.7GHz",
        memory: "8 GB",
        diskSize: "256 GB",
        chargerType: "60W MagSafe 2",
        chargerIncluded: "N",
        condition: "A",
        value: "220",
        soldPrice: "",
        dateDonated: "11/30/21",
        notes: "",
        listPrice: "",
        donatedBy: "OrderMyGear"
    },
    {
        serial: "C02RN8RWFVH5",
        laptopId: "N8RW",
        status: "",
        model: "MacBookPro12,1",
        screenSize: "",
        cpuType: "Core i5 2.7GHz",
        memory: "8 GB",
        diskSize: "256 GB",
        chargerType: "60W MagSafe 2",
        chargerIncluded: "Y",
        condition: "B",
        value: "300",
        soldPrice: "",
        dateDonated: "11/2/21",
        notes: "",
        listPrice: "",
        donatedBy: "OrderMyGear"
    },
    {
        serial: "C02QQBCCFVH5",
        laptopId: "QBCC",
        status: "",
        model: "MacBookPro12,1",
        screenSize: "",
        cpuType: "Core i5 2.7GHz",
        memory: "8 GB",
        diskSize: "256 GB",
        chargerType: "60W MagSafe 2",
        chargerIncluded: "Y",
        condition: "B",
        value: "300",
        soldPrice: "",
        dateDonated: "11/30/21",
        notes: "",
        listPrice: "",
        donatedBy: "OrderMyGear"
    },
    {
        serial: "C02QQLEJFVH5",
        laptopId: "QLEJ",
        status: "",
        model: "MacBookPro12,1",
        screenSize: "",
        cpuType: "Core i5 2.7GHz",
        memory: "8 GB",
        diskSize: "256 GB",
        chargerType: "60W MagSafe 2",
        chargerIncluded: "Y",
        condition: "B",
        value: "300",
        soldPrice: "",
        dateDonated: "11/30/21",
        notes: "",
        listPrice: "",
        donatedBy: "OrderMyGear"
    },
    {
        serial: "C02RTJKZFVH5",
        laptopId: "TJKZ",
        status: "",
        model: "MacBookPro12,1",
        screenSize: "",
        cpuType: "Core i5 2.7GHz",
        memory: "8 GB",
        diskSize: "256 GB",
        chargerType: "60W MagSafe 2",
        chargerIncluded: "Y",
        condition: "B",
        value: "300",
        soldPrice: "",
        dateDonated: "11/30/21",
        notes: "",
        listPrice: "",
        donatedBy: "OrderMyGear"
    },
    {
        serial: "C02RTN5YFVH5",
        laptopId: "TN5Y",
        status: "",
        model: "MacBookPro12,1",
        screenSize: "",
        cpuType: "Core i5 2.7GHz",
        memory: "8 GB",
        diskSize: "256 GB",
        chargerType: "60W MagSafe 2",
        chargerIncluded: "Y",
        condition: "C",
        value: "60",
        soldPrice: "",
        dateDonated: "11/30/21",
        notes: "",
        listPrice: "",
        donatedBy: "OrderMyGear"
    }
];

const InventoryPage = () => {
    const [allLaptops, setAllLaptops] = useState([]);
    const [filteredLaptops, setFilteredLaptops] = useState([]);
    const [filters, setFilters] = useState({
        search: '',
        manufacturer: '',
        status: '',
        donatedBy: '',
        screenSize: '',
        memory: '',
        diskSize: '',
        condition: '',
        chargerIncluded: '',
    });
    const [options, setOptions] = useState({
        manufacturer: [],
        status: [],
        donatedBy: [],
        screenSize: [],
        memory: [],
        diskSize: [],
        condition: [],
        chargerIncluded: [],
    });
    const [modalOpen, setModalOpen] = useState(false);
    const [modalData, setModalLaptopData] = useState({
        serial: '',
        manufacturer: '',
        laptopId: '',
        status: 'UNPROCESSED',
        donatedBy: '',
        dateDonated: '',
        model: '',
        screenSize: '',
        cpuType: '',
        memory: '',
        diskSize: '',
        condition: '',
        chargerType: '',
        chargerIncluded: false,
        value: '',
        listPrice: '',
        soldPrice: '',
        notes: '',
    });

    useEffect(() => {
        if (!allLaptops.length) {
            // Invoke get all (except archived) laptops api call
            setAllLaptops(dummyLaptopData);
        }
    }, [allLaptops.length])

    useEffect(() => {
        // Loop through laptops and populate options dropdowns
        const opts = { ...options };
        allLaptops.forEach(laptop => {
            if (opts.manufacturer.indexOf(laptop.manufacturer) === -1) opts.manufacturer.push(laptop.manufacturer);
            if (opts.status.indexOf(laptop.status) === -1) opts.status.push(laptop.status);
            if (opts.donatedBy.indexOf(laptop.donatedBy) === -1) opts.donatedBy.push(laptop.donatedBy);
            if (opts.screenSize.indexOf(laptop.screenSize) === -1) opts.screenSize.push(laptop.screenSize);
            if (opts.memory.indexOf(laptop.memory) === -1) opts.memory.push(laptop.memory);
            if (opts.diskSize.indexOf(laptop.diskSize) === -1) opts.diskSize.push(laptop.diskSize);
            if (opts.condition.indexOf(laptop.condition) === -1) opts.condition.push(laptop.condition);
            if (opts.chargerIncluded.indexOf(laptop.chargerIncluded) === -1) opts.chargerIncluded.push(laptop.chargerIncluded);
        });
        setOptions(opts);
    }, [allLaptops]);

    useEffect(() => {
        let newList = [...allLaptops];
        if (filters.search) {
            newList = newList.filter(laptop => searchCheck(laptop, filters.search.toLowerCase()));
        }
        if (filters.manufacturer) {
            newList = newList.filter(laptop => laptop.manufacturer === filters.manufacturer);
        }
        if (filters.status) {
            newList = newList.filter(laptop => laptop.status === filters.status);
        }
        if (filters.donatedBy) {
            newList = newList.filter(laptop => laptop.donatedBy === filters.donatedBy);
        }
        if (filters.screenSize) {
            newList = newList.filter(laptop => laptop.screenSize === filters.screenSize);
        }
        if (filters.memory) {
            newList = newList.filter(laptop => laptop.memory === filters.memory);
        }
        if (filters.diskSize) {
            newList = newList.filter(laptop => laptop.diskSize === filters.diskSize);
        }
        if (filters.condition) {
            newList = newList.filter(laptop => laptop.condition === filters.condition);
        }
        if (filters.chargerIncluded) {
            if (filters.chargerIncluded === 'Yes') {
                newList = newList.filter(laptop => laptop.chargerIncluded);
            } else if (filters.chargerIncluded === 'No') {
                newList = newList.filter(laptop => !laptop.chargerIncluded);
            }
        }
        setFilteredLaptops(newList);

    }, [allLaptops, filters, filters.search]);

    function searchCheck(laptop, text) {
        if (laptop.serial?.toLowerCase().includes(text)) return true;
        if (laptop.manufacturer?.toLowerCase().includes(text)) return true;
        if (laptop.laptopId?.toLowerCase().includes(text)) return true;
        if (laptop.status?.toLowerCase().includes(text)) return true;
        if (laptop.donatedBy?.toLowerCase().includes(text)) return true;
        if (laptop.dateDonated?.toLowerCase().includes(text)) return true;
        if (laptop.model?.toLowerCase().includes(text)) return true;
        if (laptop.screenSize?.toLowerCase().includes(text)) return true;
        if (laptop.cpuType?.toLowerCase().includes(text)) return true;
        if (laptop.memory?.toLowerCase().includes(text)) return true;
        if (laptop.diskSize?.toLowerCase().includes(text)) return true;
        if (laptop.condition?.toLowerCase().includes(text)) return true;
        if (laptop.chargerType?.toLowerCase().includes(text)) return true;
        if (laptop.notes?.toLowerCase().includes(text)) return true;
        return false;
    }

    function openModal(targetSerial) {
        setModalLaptopData(allLaptops.find(laptop => laptop.serial === targetSerial));
        setModalOpen(true);
    }

    function closeModal() {
        setModalOpen(false);
        setModalLaptopData({
            serial: '',
            manufacturer: '',
            laptopId: '',
            status: 'UNPROCESSED',
            donatedBy: '',
            dateDonated: '',
            model: '',
            screenSize: '',
            cpuType: '',
            memory: '',
            diskSize: '',
            condition: '',
            chargerType: '',
            chargerIncluded: false,
            value: '',
            listPrice: '',
            soldPrice: '',
            notes: '',
        });
    }

    function exportData() {
        const csvContent = [
            [
                'Serial',
                'Manufacturer',
                'Laptop ID',
                'Status',
                'Donated By',
                'Date Donated',
                'Model',
                'Screen Size',
                'CPU Type',
                'Memory',
                'Disk Size',
                'Condition',
                'Charger Type',
                'Charger Included',
                'Trade-In Value',
                'List Price',
                'Sold Price',
                'Notes',
            ],
            ...filteredLaptops.map(laptop => [
                `"${laptop.serial?.replace(`"`, `""`)}"`,
                `"${laptop.manufacturer?.replace(`"`, `""`)}"`,
                `"${laptop.laptopId?.replace(`"`, `""`)}"`,
                `"${laptop.status?.replace(`"`, `""`)}"`,
                `"${laptop.donatedBy?.replace(`"`, `""`)}"`,
                `"${laptop.dateDonated?.replace(`"`, `""`)}"`,
                `"${laptop.model?.replace(`"`, `""`)}"`,
                `"${laptop.screenSize?.replace(`"`, `""`)}"`,
                `"${laptop.cpuType?.replace(`"`, `""`)}"`,
                `"${laptop.memory?.replace(`"`, `""`)}"`,
                `"${laptop.diskSize?.replace(`"`, `""`)}"`,
                `"${laptop.condition?.replace(`"`, `""`)}"`,
                `"${laptop.chargerType?.replace(`"`, `""`)}"`,
                `"${laptop.chargerIncluded}"`,
                `"${laptop.value?.replace(`"`, `""`)}"`,
                `"${laptop.listPrice?.replace(`"`, `""`)}"`,
                `"${laptop.soldPrice?.replace(`"`, `""`)}"`,
                `"${laptop.notes?.replace(`"`, `""`)}"`,
            ])
        ]
            .map(item => item.join(","))
            .join("\n");

        let downloadLink = document.createElement('a');
        downloadLink.href = 'data:text/csv;charset=utf-8,' + encodeURI(csvContent);
        downloadLink.target = '_blank';
        downloadLink.download = 'filtered_laptop_inventory.csv';
        downloadLink.click();
    }

    return <>
        <Container sx={{ maxWidth: '1220px', margin: '24px auto 0;' }} >
            <FilterFields
                filters={filters}
                setFilters={setFilters}
                options={options}
            />
            <FilterChips
                filters={filters}
                setFilters={setFilters}
            />
            <LaptopTable
                laptops={filteredLaptops}
                filtered={allLaptops.length !== filteredLaptops.length}
                openModal={openModal}
                exportData={exportData}
            />
        </Container>

        <LaptopDetailModal
            open={modalOpen}
            close={closeModal}
            laptop={modalData}
        />
    </>;
}
export default InventoryPage;